server:
  port: 8000
  servlet:
    context-path: /consumer

spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 124.223.42.211:8848
        ip: 124.223.42.211

